### ISSUE TITLE
apb_cov의 Instance name에 대해

### ISSUE THREAD

**Issue by HIDDEN-IU** [ECE4278/lab5#1]
lab5 pdf 26페이지의 How 4번에
Instantiate the coverage group (instance name: aw_cov)라고 되어 있어
인스턴스명을 aw_cov라고 설정하라고 이해했습니다.

반면 DMAC_TB 의 apb_cov는 
apb_cov     apb_cov_inst ~~~ 형태로, 
모듈만 instantiate 해본 제가 생각하기에는 apb_cov_inst가 instance name자리에 있는 것 같습니다.

---질문---
1. coverage instantiation은  [모듈명 인스턴스명 포트] 구조의 module instantiation 문법과 달리 [인스턴스명 커버리지명] 구조의 문법을 사용하나요?
2. 그렇다면 aw_cov aw_cov_inst ~~~~라고 instantiate 해도 감점이 없을까요?

아래 사진은 sv 매뉴얼에서 module instantiation 부분을 가져왔습니다.
(hierarchical_instance ::= name_of_instance)

![image](https://user-images.githubusercontent.com/87434875/195266127-5361bfbb-e4d9-4e45-8a30-efea8f7ac06b.png)

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 

1. coverage instantiation은 [covergroup이름 인스턴스이름] 이 맞습니다. 
2. PPT에서 약간 잘못 언급됐는데 "covergroup명이 aw_cov"여야 합니다. 
    따라서 2번에서 질문하신 것과 같은 경우에는 감점 사항이 아닙니다. (instance name은 어떤 것으로 해도 무방하며, 제출하신 코드를 가지고 컴파일하고 verdi4cov 실행했을 때 expected output과 같은 그림이 나오면 됩니다.)
    

박태원 드림
